version: 2.0

jobs:
  build:
    parameters:
      configuration-path:
        description: 'Path to Allure configuration, uses default one if omitted'
        type: string
        default: /usr/local/share/allure/config/allure.yml
      target-path:
        description: Path for report directory
        type: string
        default:  ~/AlphaSenseTestFramework/backend-tests/target/allure-report
      results-path:
        description: Path to directory with test results
        type: string
        default:  ~/AlphaSenseTestFramework/backend-tests/target/allure-results
      artifact-path:
        description: Path that will be used when storing result as artifact
        type: string
        default: Report/Allure
    docker:
      - image: circleci/openjdk:8-jdk-stretch-browsers
        environment:
          MAVEN_OPTS: -Xmx1024m
    working_directory: ~/AlphaSenseTestFramework/
    steps:
      - run:
          name: Allure archive download
          command: >-
            curl -L https://github.com/allure-framework/allure2/releases/download/<<
            parameters.version >>/allure-commandline-<< parameters.version >>.zip -o
            /tmp/allure.zip
      - run:
          name: Archive extraction
          command: unzip /tmp/allure.zip
      - run:
          name: Allure installation
          command: sudo mv allure-<< parameters.version >> /usr/local/share/allure
      - run:
          name: Allure binary symlinking
          command: sudo ln -s /usr/local/share/allure/bin/allure /usr/local/bin/allure
      - checkout:
          path: ~/AlphaSenseTestFramework
      - run:
          name: Resolve Maven dependencies
          command: mvn dependency:go-offline compile compiler:testCompile
      - run:
          name:  Maven clean
          command: mvn clean
      - run:
          name:  Maven tests
          command: mvn test -Dcucumber.options="--tags '@category-all' --plugin io.qameta.allure.cucumber4jvm.AllureCucumber4Jvm" -am -pl backend-tests
#      - store_test_results:
#          path: ~/AlphaSenseTestFramework/backend-tests/target/allure-results
#      - store_artifacts:
#          path: ~/AlphaSenseTestFramework/backend-tests/target/allure-results
      - run:
          name: >-
            Allure report generation (<< parameters.results-path >> -> << parameters.target-path >>)
          command: |
            allure generate \
              --config '/usr/local/share/allure/config/allure.yml' \
              --report-dir '~/AlphaSenseTestFramework/backend-tests/target/allure-report' \
              '~/AlphaSenseTestFramework/backend-tests/target/allure-results'
      - store_artifacts:
          path: << parameters.target-path >>
          destination: << parameters.artifact-path >>